services:
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  metabase:
    image: metabase/metabase
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabaseappdb
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=password
      - MB_DB_HOST=postgres
  setup:
    build: ./setup
    environment:
      - METABASE_HOST=metabase
      - METABASE_PORT=3000
      - METABASE_EMAIL=me@meta.base
      - METABASE_PASS=MetaPass123
volumes:
  postgres-data:
  metabase-data:
